### ISSUE TITLE
sed.wavelength_grid=None

### ISSUE THREAD

**Issue by brentmsmith** [mboquien/cigale#19]
After running `pcigale check` in my data directory, I get the error: TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'.
I'm not sure why this wavelength_grid is being set to None, but the sed object seems to exist. This is occurring in pcigale/sed_modules/redshifting.py at line 188: `sed.wavelength_grid *= 1. + redshift`.  I verified that the `redshift` variable is not None but a float.

**Comment by mboquien** [comment]
Can you try to regenerate your pcigale.ini file after erasing it as well as pcigale.ini.spec. If it keeps occurring, could you attach these files please? Thanks!

**Comment by brentmsmith** [comment]
@mboquien Thanks for taking a look, attached are the two files. I had to change the extension to txt so they'd upload. 
[pcigale.ini.spec.txt](https://github.com/mboquien/cigale/files/9169578/pcigale.ini.spec.txt)
[pcigale.ini.txt](https://github.com/mboquien/cigale/files/9169579/pcigale.ini.txt)

**Comment by mboquien** [comment]
You need to move `redshifting` to the end of the list of the `sed_modules` parameter line 54 of the `pcigale.ini` file. I believe it should work after this.

**Comment by brentmsmith** [comment]
That did indeed, thank you!
