### ISSUE TITLE
Segfault triggers broken pipe in multiprocessors 

### ISSUE THREAD

**Issue by Bovornpratch** [mboquien/cigale#65]
Hello,

I found an issue that confused me. I was running CIGALE and received a segmentation fault during the model computation phase which triggered a broken pipe in the multiprocessors module. When this happens, the cores die off one by one and the multiprocessor is left waiting for the return from each CPU. This results in the system holding memory but with no models being computed.

One thing I found was that this occurred when I changed the parameter redshift_decimals from 2 to 3. However, due to the long time in the computation, it is hard to tell what triggers the error. 

Has this kind of issue been brought up before?

<img width="1252" alt="Screen Shot 2023-09-05 at 17 09 23" src="https://github.com/mboquien/cigale/assets/20829556/1936cd63-ec3a-4481-ba5b-8d01902a14a8">

Some info on the system.
Python 3.10.12
astropy         5.3.2
configobj       5.0.8
contourpy       1.1.0
cycler          0.11.0
fonttools       4.42.1
kiwisolver      1.4.5
markdown-it-py  3.0.0
matplotlib      3.7.2
mdurl           0.1.2
numpy           1.25.2
packaging       23.1
pcigale         2022.1 
Pillow          10.0.0
pip             22.0.2
pyerfa          2.0.0.3
Pygments        2.16.1
pyparsing       3.0.9
python-dateutil 2.8.2
PyYAML          6.0.1
rich            13.5.2
scipy           1.11.2
setuptools      59.6.0
six             1.16.0

**Comment by mboquien** [comment]
This can happen when you run out of memory. What I would suggest, besides getting more memory, is to increase the value of the `blocks` parameter in the `pdf_analysis` module. It will reduce the memory requirements at the expense of a slightly slower computation time.
