### ISSUE TITLE
Fritz model

### ISSUE THREAD

**Issue by Bastiebb** [mboquien/cigale#88]
[Error_Fritz.txt](https://github.com/mboquien/cigale/files/15200987/Error_Fritz.txt)
Hello, I have been working with Cigale for a week and a half now and I created some SEDs with Cigale using the SKIRTOR model, but when I try to use the Fritz model I end up getting an error when I do pcigale check. I use Fritz2006 and the xray package

'The information agn.intrin_Lnu_2500A_30deg is already present in the SED. '

I even get this error when I don't change any parameters after the genconf.
Any help would be amazing, thank you

**Comment by Guang91** [comment]
I can't reproduce your error with Friz model. Could you share your pcigale.ini and pcigale.ini.spec files?

**Comment by Bastiebb** [comment]
[pcigale.ini.spec.txt](https://github.com/mboquien/cigale/files/15201271/pcigale.ini.spec.txt)
[pcigaletxt.txt](https://github.com/mboquien/cigale/files/15201276/pcigaletxt.txt)
Here are the files

**Comment by Guang91** [comment]
The module "redshiftting" should be at the end of the all module.
Could you try that and "pcigale genconf" again?

-Guang

**Comment by Bastiebb** [comment]
Sadly that doesn't work I tried it now and I still get the same error

**Comment by Guang91** [comment]
Oops, I found another error. "xray“ should follow "fritz2006”, as the document says "The module names should follow the order given in the commentary parts."

**Comment by Bastiebb** [comment]
Perfect! thank you this helped
